/**
 * Style Dictionary config — generates constants/*.ts from tokens/tokens.json
 *
 * Handles Figma Tokens Studio multi-set format with cross-set reference
 * resolution. Includes hardcoded fallbacks for React Native-specific values
 * (font variant names, semantic typography compositions) that Tokens Studio
 * does not manage.
 */
import { readFileSync } from 'fs';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function loadResolvedTokens() {
  const raw = JSON.parse(readFileSync('tokens/tokens.json', 'utf8'));
  const setOrder = raw.$metadata?.tokenSetOrder || [];

  const flat = {};
  for (const setName of setOrder) {
    const setData = raw[setName];
    if (!setData) continue;
    flattenSet(setData, '', flat);
  }

  for (const key of Object.keys(flat)) {
    flat[key] = resolve(flat[key], flat);
  }

  return { raw, flat, setOrder };
}

function flattenSet(obj, prefix, flat) {
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    const path = prefix ? `${prefix}.${key}` : key;
    if (isToken(val)) {
      flat[path] = tokenValue(val);
    } else if (val && typeof val === 'object') {
      flattenSet(val, path, flat);
    }
  }
}

function resolve(value, flat, depth = 0) {
  if (depth > 10) return value;
  if (typeof value !== 'string') return value;
  const m = value.match(/^\{(.+)\}$/);
  if (!m) return value;
  if (flat[m[1]] !== undefined) return resolve(String(flat[m[1]]), flat, depth + 1);
  return value;
}

function lit(v) {
  if (v === undefined || v === null) return "''";
  const str = String(v);
  if (/^#[0-9a-fA-F]{3,8}$/.test(str)) return `'${str.toUpperCase()}'`;
  const n = Number(str);
  if (!isNaN(n) && str !== '' && str !== 'true' && str !== 'false') return String(n);
  return `'${str}'`;
}

function kebabToCamel(s) {
  return s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function obj(entries, indent = '  ') {
  const lines = entries.map(([k, v]) => {
    const needsQuote = /^\d/.test(k) || !/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k);
    const key = needsQuote ? `'${k}'` : k;
    return `${indent}${key}: ${v},`;
  });
  return `{\n${lines.join('\n')}\n}`;
}

// DTCG-aware token accessors — support W3C DTCG (`$value`/`$type`) and the
// legacy Tokens Studio format (`value`/`type`) transparently.
function isToken(node) {
  return !!node && typeof node === 'object' && ('$value' in node || 'value' in node);
}
function tokenValue(node) {
  if (!node || typeof node !== 'object') return undefined;
  return '$value' in node ? node.$value : node.value;
}
function tokenType(node) {
  if (!node || typeof node !== 'object') return undefined;
  return '$type' in node ? node.$type : node.type;
}

const HEADER = '// Auto-generated by Style Dictionary — do not edit manually\n';

// ---------------------------------------------------------------------------
// RN-specific fallbacks (not managed by Tokens Studio)
// ---------------------------------------------------------------------------

/** React Native / Expo font variant names. */
const FONT_FAMILY = {
  // Source Serif 4 + Albert Sans
  sourceSerifRegular: 'SourceSerif4_400Regular',
  sourceSerifItalic: 'SourceSerif4_400Regular_Italic',
  sourceSerifSemiBold: 'SourceSerif4_600SemiBold',
  sourceSerifBold: 'SourceSerif4_700Bold',
  albertSansMedium: 'AlbertSans_500Medium',
  albertSansSemiBold: 'AlbertSans_600SemiBold',
  displaySemiBold: 'BarlowCondensed_600SemiBold',
  displayBold: 'BarlowCondensed_700Bold',
  displayExtraBold: 'BarlowCondensed_800ExtraBold',
  bodyRegular: 'Inter_400Regular',
  bodyMedium: 'Inter_500Medium',
  bodySemiBold: 'Inter_600SemiBold',
  bodyBold: 'Inter_700Bold',
  monoRegular: 'JetBrainsMono_400Regular',
  monoMedium: 'JetBrainsMono_500Medium',
};

/** Tokens Studio named weight → numeric (for typeStyles font lookup). */
const NAMED_WEIGHT = {
  Thin: '100', ExtraLight: '200', Light: '300', Regular: '400',
  Medium: '500', SemiBold: '600', Bold: '700', ExtraBold: '800', Black: '900',
};

/** Map token font-family + weight to Expo variant name (incl. italic variants). */
const EXPO_FONT_NAME = {
  // Source Serif 4 (Tokens Studio family name: "Source Serif Pro")
  'Source Serif Pro_400':         'SourceSerif4_400Regular',
  'Source Serif Pro_400_italic':  'SourceSerif4_400Regular_Italic',
  'Source Serif Pro_600':         'SourceSerif4_600SemiBold',
  'Source Serif Pro_600_italic':  'SourceSerif4_600SemiBold_Italic',
  'Source Serif Pro_700':         'SourceSerif4_700Bold',
  'Source Serif Pro_700_italic':  'SourceSerif4_700Bold_Italic',
  // Albert Sans
  'Albert Sans_500':         'AlbertSans_500Medium',
  'Albert Sans_500_italic':  'AlbertSans_500Medium',
  'Albert Sans_600':         'AlbertSans_600SemiBold',
};

/** typeStyles entries that should use the italic font variant. */
const ITALIC_TYPE_STYLES = new Set(['italicConnector', 'heroDisplay', 'textLink']);

/** Font sizes missing from the primitive scale but referenced in existing code. */
const EXTRA_FONT_SIZES = { 12: 12, 20: 20, 24: 24, 30: 30, 48: 48, 60: 60, 72: 72 };

/**
 * Semantic typography compositions. Uses primitive lineHeight multipliers
 * and letter-spacing values (em-relative, converted to px at build time).
 */
const SEMANTIC_TYPOGRAPHY = {
  display: [
    { size: '2xl', ff: 'displayBold',     fs: 72, lh: 1.1,  ls: -0.02 },
    { size: 'xl',  ff: 'displayBold',     fs: 60, lh: 1.1,  ls: -0.02 },
    { size: 'lg',  ff: 'displayBold',     fs: 48, lh: 1.1,  ls: -0.02 },
    { size: 'md',  ff: 'displaySemiBold', fs: 36, lh: 1.25, ls: 0 },
    { size: 'sm',  ff: 'displaySemiBold', fs: 30, lh: 1.25, ls: 0 },
  ],
  body: [
    { size: 'xl', ff: 'bodyRegular', fs: 20, lh: 1.5 },
    { size: 'lg', ff: 'bodyRegular', fs: 18, lh: 1.5 },
    { size: 'md', ff: 'bodyRegular', fs: 16, lh: 1.5 },
    { size: 'sm', ff: 'bodyRegular', fs: 14, lh: 1.5 },
    { size: 'xs', ff: 'bodyRegular', fs: 12, lh: 1.5 },
  ],
  label: [
    { size: 'lg',   ff: 'bodySemiBold', fs: 18, lh: 1.25 },
    { size: 'md',   ff: 'bodySemiBold', fs: 16, lh: 1.25 },
    { size: 'sm',   ff: 'bodyMedium',   fs: 14, lh: 1.25 },
    { size: 'caps', ff: 'bodySemiBold', fs: 12, lh: 1.25, ls: 0.15, tt: 'uppercase' },
  ],
  mono: [
    { size: 'xl', ff: 'monoMedium',  fs: 20, lh: 1.1 },
    { size: 'lg', ff: 'monoMedium',  fs: 18, lh: 1.1 },
    { size: 'md', ff: 'monoRegular', fs: 16, lh: 1.1 },
    { size: 'sm', ff: 'monoRegular', fs: 14, lh: 1.1 },
  ],
};

/** Fallback color tokens for values not yet in Tokens Studio. */
const COLOR_FALLBACKS = {
  text: { inverse: '{color.neutral.950}' },
  border: {
    'border-default': '{color.neutral.700}',
    'border-subtle': '{color.neutral.800}',
    'border-focus': '{color.blue.300}',
  },
};

// ---------------------------------------------------------------------------
// Composite-token literal builders (typography objects, boxShadow arrays)
// ---------------------------------------------------------------------------
// Composite tokens (DTCG `typography` and `boxShadow`) have object/array values.
// The naive `String(value)` used for scalar tokens collapses these to the
// literal '[object Object]'; these builders resolve them into React-Native-usable
// literals instead (a TextStyle object, resp. an RN `boxShadow` array).

/** Resolve a composite reference (e.g. "{type.buttonPrimary}") to its raw value. */
function derefComposite(ref, flat) {
  if (typeof ref !== 'string') return ref;
  const m = ref.match(/^\{(.+)\}$/);
  return m && flat[m[1]] !== undefined ? flat[m[1]] : ref;
}

/** Convert %-string or numeric letterSpacing to absolute px given fontSize. */
function lsToAbsPx(raw, fs) {
  if (raw == null || raw === '0') return 0;
  const s = String(raw);
  if (s.endsWith('%')) return Math.round(fs * (parseFloat(s) / 100) * 1000) / 1000;
  const n = Number(s);
  return isNaN(n) ? 0 : n;
}

/** Build an RN TextStyle object literal from a typography composite token. */
function typographyLiteral(ref, flat) {
  const comp = derefComposite(ref, flat);
  if (!comp || typeof comp !== 'object') return 'undefined';
  const familyRaw = String(resolve(String(comp.fontFamily ?? ''), flat));
  const weightFull = String(resolve(String(comp.fontWeight ?? '400'), flat));
  const weight = /^\d+$/.test(weightFull) ? weightFull : (NAMED_WEIGHT[weightFull] || '400');
  const fs = Number(resolve(String(comp.fontSize ?? 0), flat)) || 0;
  const lhRaw = resolve(String(comp.lineHeight ?? ''), flat);
  const lhFactor = (() => {
    const s = String(lhRaw ?? '');
    if (!s || s === 'AUTO' || s === 'auto') return 1;
    if (s.endsWith('%')) return parseFloat(s) / 100;
    return Number(s) || 1;
  })();
  const lh = Math.round(fs * lhFactor * 100) / 100;
  const ls = lsToAbsPx(resolve(String(comp.letterSpacing ?? '0'), flat), fs);
  const expoName = EXPO_FONT_NAME[`${familyRaw}_${weight}`] || `${familyRaw}_${weight}`;
  const parts = [`fontFamily: '${expoName}'`, `fontSize: ${fs}`, `lineHeight: ${lh}`];
  if (ls !== 0) parts.push(`letterSpacing: ${ls}`);
  return `{ ${parts.join(', ')} }`;
}

/** Build an RN `boxShadow` array literal from a boxShadow composite token. */
function shadowLiteral(ref, flat) {
  const val = derefComposite(ref, flat);
  const layers = Array.isArray(val) ? val : (val && typeof val === 'object' ? [val] : []);
  if (layers.length === 0) return '[]';
  const num = (x) => Number(x) || 0;
  const items = layers.map((l) => {
    const color = String(resolve(String(l.color ?? ''), flat));
    const inset = l.type === 'innerShadow';
    return `        { offsetX: ${num(l.x)}, offsetY: ${num(l.y)}, blurRadius: ${num(l.blur)}, ` +
      `spreadDistance: ${num(l.spread)}, color: '${color}', inset: ${inset} }`;
  });
  return `[\n${items.join(',\n')},\n      ]`;
}

// ---------------------------------------------------------------------------
// Format: ts/colors
// ---------------------------------------------------------------------------

function formatColors() {
  const { raw, flat, setOrder } = loadResolvedTokens();
  const primSet = raw[setOrder[0]] || {};
  const tokSet = raw[setOrder[1]] || {};

  function colorScale(colorName) {
    const group = primSet.color?.[colorName] || {};
    return Object.keys(group)
      .filter(k => !k.startsWith('$'))
      .map(k => [k, lit(flat[`color.${colorName}.${k}`])]);
  }

  function semanticColorGroup(groupPath, stripPrefix = '') {
    const parts = groupPath.split('.');
    let group = tokSet;
    for (const p of parts) group = group?.[p] || {};
    return Object.keys(group)
      .filter(k => !k.startsWith('$') && isToken(group[k]))
      .map(k => {
        const cleanKey = stripPrefix && k.startsWith(`${stripPrefix}-`)
          ? k.slice(stripPrefix.length + 1)
          : k;
        return [kebabToCamel(cleanKey), lit(flat[`${groupPath}.${k}`])];
      });
  }

  const neutralEntries = colorScale('neutral');
  // Semantic color groups — resolved from Theme set (bg / fg / accent / border / achievement)
  const bgEntries = semanticColorGroup('bg');
  const fgEntries = semanticColorGroup('fg');
  const accentEntries = semanticColorGroup('accent');
  const borderEntries = semanticColorGroup('border');
  const achievementEntries = semanticColorGroup('achievement');

  // --- Component tokens (from components set) ---
  const compSet = raw[setOrder[2]] || {};
  const buttonGroup = compSet.button || {};
  const buttonVariants = [];

  for (const [variant, def] of Object.entries(buttonGroup)) {
    if (variant.startsWith('$')) continue;
    if (isToken(def)) {
      // top-level prop like radius — skip for buttonTokens
      continue;
    }
    const props = [];
    for (const [prop, val] of Object.entries(def)) {
      if (prop.startsWith('$') || !isToken(val)) continue;
      const type = tokenType(val);
      const raw = tokenValue(val);
      if (type === 'typography') {
        props.push([prop, typographyLiteral(raw, flat)]);
      } else if (type === 'boxShadow') {
        props.push([prop, shadowLiteral(raw, flat)]);
      } else {
        props.push([prop, lit(resolve(String(raw), flat))]);
      }
    }
    // compat: add .text alias for .color so existing components work
    const colorEntry = props.find(([k]) => k === 'color');
    if (colorEntry && !props.find(([k]) => k === 'text')) {
      props.push(['text', colorEntry[1]]);
    }
    if (props.length > 0) {
      const inner = props.map(([k, v]) => `      ${k}: ${v},`).join('\n');
      buttonVariants.push(`    ${variant}: {\n${inner}\n    }`);
    }
  }

  const buttonRadius = isToken(buttonGroup.radius)
    ? `    radius: ${lit(resolve(String(tokenValue(buttonGroup.radius)), flat))},`
    : `    radius: 22,`; // compat: matches primary.radius for shared button borderRadius

  const buttonTokensBody = buttonVariants.length > 0
    ? `{\n${buttonVariants.join(',\n')},\n${buttonRadius ? `${buttonRadius}\n` : ''}  }`
    : '{}';

  // --- progressBar tokens ---
  const progressBarEntries = [
    ['trackColor', lit(flat['progressBar.trackColor'] || '')],
    ['successFill', lit(flat['progressBar.fillSucces'] || '')],  // token has typo: fillSucces
    ['warningFill', lit(flat['progressBar.warningFill'] || '')],
  ];

  return `${HEADER}
export const neutral = ${obj(neutralEntries)} as const;

export const bg = ${obj(bgEntries)} as const;

export const fg = ${obj(fgEntries)} as const;

export const accent = ${obj(accentEntries)} as const;

export const border = ${obj(borderEntries)} as const;

export const achievement = ${obj(achievementEntries)} as const;

export const buttonTokens = ${buttonTokensBody} as const;

export const progressBar = ${obj(progressBarEntries)} as const;

// Backwards-compat aliases — existing components still reference these names
export const background = { ...bg, surface: bg.elevated } as const;
export const text = { ...fg, muted: fg.tertiary, inverse: fg.onAccent } as const;
export const brand = { primary: accent.default, secondary: accent.hover } as const;
export const status = { success: '#22C55E', warning: '#F59E0B', error: '#EF4444' } as const;
export const blue = {} as const;

export const colors = {
  neutral,
  bg,
  fg,
  accent,
  border,
  buttonTokens,
} as const;
`;
}

// ---------------------------------------------------------------------------
// Format: ts/spacing
// ---------------------------------------------------------------------------

function formatSpacing() {
  const { raw, flat, setOrder } = loadResolvedTokens();
  // Raw spacing values live in Core.spacing (not Theme.spacing which doesn't exist)
  const primSet = raw[setOrder[0]] || {};
  const spacingGroup = primSet.spacing || {};

  const spaceEntries = Object.keys(spacingGroup)
    .filter(k => !k.startsWith('$'))
    .sort((a, b) => Number(a) - Number(b))
    .map(k => [k, lit(flat[`spacing.${k}`])]);

  // Backwards-compat Tailwind-style indices (old space used Tailwind scale: 1=4, 2=8, 3=12, 4=16, 5=20, 6=24)
  const TAILWIND_COMPAT = { '1': 4, '3': 12, '5': 20, '7': 28 };
  for (const [k, v] of Object.entries(TAILWIND_COMPAT)) {
    if (!spaceEntries.find(([ek]) => ek === k)) {
      spaceEntries.push([k, lit(v)]);
    }
  }
  // compat: space.px = 1 used for hairline gaps/borders
  if (!spaceEntries.find(([k]) => k === 'px')) {
    spaceEntries.push(['px', '1']);
  }

  // Layout constants derived from Component tokens
  const compSet = raw[setOrder[2]] || {};
  const screenComp = compSet.screen || {};
  const tabBarComp = compSet.tabBar || {};
  const layoutEntries = [
    ['screenPaddingX',    lit(flat['screen.paddingX']    || resolve(String(tokenValue(screenComp.paddingX)  || 24), flat))],
    ['screenPaddingXAlt', lit(flat['screen.paddingXAlt'] || resolve(String(tokenValue(screenComp.paddingXAlt) || 28), flat))],
    ['tabBarPaddingTop',  lit(flat['tabBar.paddingTop']  || resolve(String(tokenValue(tabBarComp.paddingTop) || 18), flat))],
    ['tabBarPaddingBottom', lit(flat['tabBar.paddingBottom'] || resolve(String(tokenValue(tabBarComp.paddingBottom) || 28), flat))],
    // Backwards-compat aliases for pre-existing code
    ['screenHorizontal', '20'],  // was layout.screenHorizontal = 16 in old tokens
    ['navHeight', '48'],         // was layout.navHeight = 48 in old tokens
  ];

  return `${HEADER}
export const space = ${obj(spaceEntries)} as const;

export const layout = ${obj(layoutEntries)} as const;

export const spacing = {
  space,
  layout,
} as const;
`;
}

// ---------------------------------------------------------------------------
// Format: ts/radius
// ---------------------------------------------------------------------------

function formatRadius() {
  const { raw, flat, setOrder } = loadResolvedTokens();
  const primSet = raw[setOrder[0]] || {};
  const tokSet = raw[setOrder[1]] || {};

  // Primitive radii from Core.borderRadius
  const borderRadiusGroup = primSet.borderRadius || {};
  const radiiEntries = Object.keys(borderRadiusGroup)
    .filter(k => !k.startsWith('$'))
    .map(k => [k, lit(flat[`borderRadius.${k}`])]);

  // Backwards-compat radii entries
  if (!radiiEntries.find(([k]) => k === '3xl')) {
    radiiEntries.push(['3xl', '32']); // bottom sheet / large sheet corners
  }

  // Component radii from Theme.radius
  const radiusGroup = tokSet.radius || {};
  const componentEntries = Object.keys(radiusGroup)
    .filter(k => !k.startsWith('$') && isToken(radiusGroup[k]))
    .map(k => [kebabToCamel(k), lit(flat[`radius.${k}`])]);

  // Backwards-compat component radius entries
  const COMPONENT_RADIUS_COMPAT = { cardSm: 12, modal: 24 };
  for (const [k, v] of Object.entries(COMPONENT_RADIUS_COMPAT)) {
    if (!componentEntries.find(([ek]) => ek === k)) {
      componentEntries.push([k, String(v)]);
    }
  }

  return `${HEADER}
export const radii = ${obj(radiiEntries)} as const;

export const componentRadius = ${obj(componentEntries)} as const;

export const radius = {
  radii,
  component: componentRadius,
} as const;
`;
}

// ---------------------------------------------------------------------------
// Format: ts/typography
// ---------------------------------------------------------------------------

function formatTypography() {
  const { raw, flat, setOrder } = loadResolvedTokens();
  const primSet = raw[setOrder[0]] || {};
  const tokSet = raw[setOrder[1]] || {};
  // Semantic type styles live in Theme.type (not Theme.typography)
  const typo = tokSet.type || tokSet.typography || {};

  // fontFamily — always use FONT_FAMILY map (Expo variant names, not token family strings)
  const ffEntries = Object.entries(FONT_FAMILY).map(([k, v]) => [k, lit(v)]);

  // fontSize — from Core.fontSize (not Core.typography.fontSize)
  const fsPrim = primSet.fontSize || primSet.typography?.['font-size'] || primSet.typography?.fontSize || {};
  const fsMap = {};
  for (const k of Object.keys(fsPrim).filter(k => !k.startsWith('$'))) {
    fsMap[k] = flat[`fontSize.${k}`];
  }
  for (const [k, v] of Object.entries(EXTRA_FONT_SIZES)) {
    if (!(k in fsMap)) fsMap[k] = v;
  }
  const fsEntries = Object.keys(fsMap)
    .sort((a, b) => Number(a) - Number(b))
    .map(k => [k, lit(fsMap[k])]);

  // lineHeight — from Core.lineHeight
  const lhPrim = primSet.lineHeight || primSet.typography?.lineHeight || {};
  const lhEntries = Object.keys(lhPrim)
    .filter(k => !k.startsWith('$'))
    .map(k => [k, lit(flat[`lineHeight.${k}`])]);

  // letterSpacing — from Core.letterSpacing. Exported as decimal multipliers (% / 100)
  // so existing code can do: letterSpacing.wider * fontSize['60'] to get px value.
  const lsPrim = primSet.letterSpacing || primSet.typography?.letterSpacing || {};
  const lsEntries = Object.keys(lsPrim)
    .filter(k => !k.startsWith('$'))
    .map(k => {
      const raw = flat[`letterSpacing.${k}`];
      const s = String(raw ?? 0);
      const val = s.endsWith('%') ? parseFloat(s) / 100 : (Number(s) || 0);
      return [k, String(Math.round(val * 10000) / 10000)];
    });

  /** Build semantic styles from tokens or fallback definitions. */
  function semanticStyles(category) {
    // Try tokens first
    const group = typo[category];
    if (group && Object.keys(group).filter(k => !k.startsWith('$')).length > 0) {
      return semanticStylesFromTokens(group, category);
    }
    // Fallback to hardcoded definitions
    const defs = SEMANTIC_TYPOGRAPHY[category];
    if (!defs) return '{}';
    return semanticStylesFromDefs(defs);
  }

  function semanticStylesFromTokens(group, category) {
    // Build lookup from SEMANTIC_TYPOGRAPHY for RN-specific font families + extras
    const fallbackDefs = SEMANTIC_TYPOGRAPHY[category] || [];
    const fallbackMap = {};
    for (const d of fallbackDefs) fallbackMap[d.size] = d;

    const entries = [];
    for (const [size, def] of Object.entries(group)) {
      if (size.startsWith('$')) continue;
      // fontSize + lineHeight from tokens (resolveRef unwraps token objects)
      const fs = Number(resolveRef(def.fontSize));
      const lh = Number(resolveRef(def.lineHeight));
      const computed = Math.round(fs * lh * 100) / 100;
      // fontFamily from SEMANTIC_TYPOGRAPHY (RN variant name with correct weight)
      const fb = fallbackMap[size];
      const ff = fb ? (FONT_FAMILY[fb.ff] || fb.ff) : String(resolveRef(def.fontFamily));
      const props = [`    fontFamily: '${ff}'`, `    fontSize: ${fs}`, `    lineHeight: ${computed}`];
      // letterSpacing: prefer fallback (em-relative), fall back to token value
      if (fb?.ls !== undefined) {
        const lsAbs = Math.abs(fb.ls) < 1 ? Math.round(fs * fb.ls * 100) / 100 : fb.ls;
        props.push(`    letterSpacing: ${lsAbs}`);
      } else if (def.letterSpacing) {
        const lsRaw = Number(resolveRef(def.letterSpacing));
        const lsAbs = Math.abs(lsRaw) < 1 ? Math.round(fs * lsRaw * 100) / 100 : lsRaw;
        props.push(`    letterSpacing: ${lsAbs}`);
      }
      // textTransform from fallback or token
      if (fb?.tt) {
        props.push(`    textTransform: '${fb.tt}' as const`);
      } else if (def.textTransform) {
        props.push(`    textTransform: '${def.textTransform}' as const`);
      }
      const key = /^\d/.test(size) || size.includes('xl') ? `'${size}'` : size;
      entries.push(`  ${key}: {\n${props.join(',\n')},\n  }`);
    }
    return `{\n${entries.join(',\n')},\n}`;
  }

  function semanticStylesFromDefs(defs) {
    const entries = [];
    for (const d of defs) {
      const ff = FONT_FAMILY[d.ff] || d.ff;
      const computed = Math.round(d.fs * d.lh * 100) / 100;
      const props = [`    fontFamily: '${ff}'`, `    fontSize: ${d.fs}`, `    lineHeight: ${computed}`];
      if (d.ls !== undefined) {
        const lsAbs = Math.abs(d.ls) < 1 ? Math.round(d.fs * d.ls * 100) / 100 : d.ls;
        props.push(`    letterSpacing: ${lsAbs}`);
      }
      if (d.tt) props.push(`    textTransform: '${d.tt}' as const`);
      const key = /^\d/.test(d.size) || d.size.includes('xl') ? `'${d.size}'` : d.size;
      entries.push(`  ${key}: {\n${props.join(',\n')},\n  }`);
    }
    return `{\n${entries.join(',\n')},\n}`;
  }

  function resolveRef(val) {
    // Unwrap token objects like {$value: "{...}", $type: "fontSizes"}
    if (isToken(val)) val = tokenValue(val);
    if (typeof val !== 'string') return val;
    const m = val.match(/^\{(.+)\}$/);
    if (m && flat[m[1]] !== undefined) return flat[m[1]];
    return val;
  }

  // --- typeStyles: semantic text styles from Theme.type ---
  const typeEntries = [];
  for (const [name, def] of Object.entries(typo)) {
    if (name.startsWith('$') || !isToken(def)) continue;
    const v = tokenValue(def);
    if (typeof v !== 'object') continue;

    const familyRaw = String(resolveRef(v.fontFamily) || '');
    const weightRawFull = String(resolveRef(v.fontWeight) || '400');
    // Normalize named weights (Bold → 700, SemiBold → 600, …) to their numeric equivalent
    const weightRaw = /^\d+$/.test(weightRawFull)
      ? weightRawFull
      : (NAMED_WEIGHT[weightRawFull] || '400');
    const fs = Number(resolveRef(v.fontSize)) || 0;
    const lhRaw = resolveRef(v.lineHeight);
    const lhFactor = (() => {
      const s = String(lhRaw ?? '');
      if (!s || s === 'AUTO' || s === 'auto') return 1;
      if (s.endsWith('%')) return parseFloat(s) / 100;
      return Number(s) || 1;
    })();
    const lh = Math.round(fs * lhFactor * 100) / 100;
    const lsRaw = resolveRef(v.letterSpacing);
    const ls = lsToAbsPx(lsRaw, fs);
    const hasUppercase = v.textCase === 'uppercase';

    // Italic when explicitly in ITALIC_TYPE_STYLES or fontWeight token is the literal "Italic" style
    const isItalic = ITALIC_TYPE_STYLES.has(name) || weightRawFull === 'Italic';
    const expoKey = isItalic ? `${familyRaw}_${weightRaw}_italic` : `${familyRaw}_${weightRaw}`;
    const expoName = EXPO_FONT_NAME[expoKey] || (isItalic ? `${familyRaw}_${weightRaw}_Italic` : `${familyRaw}_${weightRaw}`);

    const props = [`    fontFamily: '${expoName}'`, `    fontSize: ${fs}`, `    lineHeight: ${lh}`];
    if (ls !== 0) props.push(`    letterSpacing: ${ls}`);
    if (hasUppercase) props.push(`    textTransform: 'uppercase' as const`);

    typeEntries.push(`  ${name}: {\n${props.join(',\n')},\n  }`);
  }
  const typeStylesBody = typeEntries.length > 0
    ? `{\n${typeEntries.join(',\n')},\n}`
    : '{}';

  return `${HEADER}
export const fontFamily = ${obj(ffEntries)} as const;

export const fontSize = ${obj(fsEntries)} as const;

export const lineHeight = ${obj(lhEntries)} as const;

export const letterSpacing = ${obj(lsEntries)} as const;

export const typeStyles = ${typeStylesBody} as const;

export const display = ${semanticStyles('display')} as const;

export const body = ${semanticStyles('body')} as const;

export const label = ${semanticStyles('label')} as const;

export const mono = ${semanticStyles('mono')} as const;

export const typography = {
  fontFamily,
  fontSize,
  lineHeight,
  letterSpacing,
  typeStyles,
  display,
  body,
  label,
  mono,
} as const;
`;
}

// ---------------------------------------------------------------------------
// Style Dictionary config
// ---------------------------------------------------------------------------

/** @type {import('style-dictionary').Config} */
export default {
  source: ['tokens/tokens.json'],
  log: {
    verbosity: 'silent',
    errors: {
      brokenReferences: 'console',
    },
  },
  platforms: {
    ts: {
      buildPath: 'constants/',
      files: [
        { destination: 'colors.ts', format: 'ts/colors' },
        { destination: 'spacing.ts', format: 'ts/spacing' },
        { destination: 'radius.ts', format: 'ts/radius' },
        { destination: 'typography.ts', format: 'ts/typography' },
      ],
    },
  },
  hooks: {
    formats: {
      'ts/colors': () => formatColors(),
      'ts/spacing': () => formatSpacing(),
      'ts/radius': () => formatRadius(),
      'ts/typography': () => formatTypography(),
    },
  },
};
