// Auto-generated by Style Dictionary — do not edit manually

export const neutral = {
  '0': '#000000',
  '50': '#F2F4FA',
  '100': '#E0E3EA',
  '200': '#B5B9C2',
  '300': '#8A8E97',
  '400': '#5C606B',
  '500': '#3A3E48',
  '600': '#2C2F37',
  '700': '#21242C',
  '800': '#1F2128',
  '900': '#1A1D24',
  '950': '#15171C',
  '1000': '#08090C',
} as const;

export const bg = {
  base: '#15171C',
  elevated: '#1A1D24',
  raised: '#21242C',
} as const;

export const fg = {
  primary: '#F2F4FA',
  secondary: '#B5B9C2',
  tertiary: '#8A8E97',
  quaternary: '#5C606B',
  onAccent: '#FFFFFF',
} as const;

export const accent = {
  default: '#F05454',
  hover: '#F66363',
  pressed: '#DC4848',
  subtle: 'rgba(240, 84, 84, 0.06)',
  muted: 'rgba(240, 84, 84, 0.12)',
} as const;

export const border = {
  subtle: '#1F2128',
  default: '#2C2F37',
  strong: '#3A3E48',
} as const;

export const achievement = {
  default: '#E8DCC4',
  muted: '#C9B894',
} as const;

export const buttonTokens = {
    primary: {
      background: '#F05454',
      color: '#FFFFFF',
      border: '#F05454',
      borderWidth: 1,
      radius: 8,
      height: 44,
      paddingX: 24,
      typography: { fontFamily: 'SourceSerif4_600SemiBold', fontSize: 18, letterSpacing: -0.27 },
      shadow: [
        { offsetX: 0, offsetY: 1, blurRadius: 0, spreadDistance: 0, color: 'rgba(255, 255, 255, 0.22)', inset: true },
        { offsetX: 0, offsetY: -2, blurRadius: 4, spreadDistance: 0, color: 'rgba(180, 40, 40, 0.30)', inset: true },
        { offsetX: 0, offsetY: 6, blurRadius: 20, spreadDistance: 0, color: 'rgba(240, 84, 84, 0.20)', inset: false },
        { offsetX: 0, offsetY: 1, blurRadius: 2, spreadDistance: 0, color: 'rgba(0, 0, 0, 0.3)', inset: false },
      ],
      gradientFrom: '#F66363',
      gradientTo: '#F05454',
      text: '#FFFFFF',
    },
    outline: {
      background: 'rgba(240, 84, 84, 0.06)',
      backgroundHover: 'rgba(240, 84, 84, 0.12)',
      color: '#F05454',
      border: '#F05454',
      borderWidth: 1,
      radius: 8,
      paddingY: 12,
      paddingX: 22,
      gap: 10,
      typography: { fontFamily: 'SourceSerif4_600SemiBold', fontSize: 16, letterSpacing: -0.24 },
      shadow: [
        { offsetX: 0, offsetY: 1, blurRadius: 0, spreadDistance: 0, color: 'rgba(255, 255, 255, 0.04)', inset: true },
      ],
      text: '#F05454',
    },
    destructive: {
      background: 'rgba(240, 84, 84, 0.06)',
      color: '#F05454',
      border: '#F05454',
      borderWidth: 1,
      radius: 8,
      height: 52,
      typography: { fontFamily: 'SourceSerif4_600SemiBold', fontSize: 16, letterSpacing: -0.24 },
      shadow: [
        { offsetX: 0, offsetY: 1, blurRadius: 0, spreadDistance: 0, color: 'rgba(255, 255, 255, 0.04)', inset: true },
      ],
      text: '#F05454',
    },
    radius: 22,
  } as const;

export const progressBar = {
  trackColor: '#C9B894',
  successFill: '#4CAF50',
  warningFill: '#FE9429',
} as const;

// Backwards-compat aliases — existing components still reference these names
export const background = { ...bg, surface: bg.elevated } as const;
export const text = { ...fg, muted: fg.tertiary, inverse: fg.onAccent } as const;
export const brand = { primary: accent.default, secondary: accent.hover } as const;
export const status = { success: '#22C55E', warning: '#F59E0B', error: '#EF4444' } as const;
export const blue = {} as const;

export const colors = {
  neutral,
  bg,
  fg,
  accent,
  border,
  buttonTokens,
} as const;
