// Auto-generated by Style Dictionary — do not edit manually

// Font-asset-map voor `useFonts(fontMap)` uit 'expo-font'. Gegenereerd uit de
// FONTS-bron in style-dictionary.config.mjs — dé enige plek voor font-gewichten.
import {
  SourceSerif4_400Regular,
  SourceSerif4_400Regular_Italic,
  SourceSerif4_600SemiBold,
  SourceSerif4_700Bold,
} from '@expo-google-fonts/source-serif-4';
import {
  AlbertSans_300Light,
  AlbertSans_400Regular,
  AlbertSans_400Regular_Italic,
  AlbertSans_500Medium,
  AlbertSans_600SemiBold,
  AlbertSans_700Bold,
} from '@expo-google-fonts/albert-sans';
import {
  BarlowCondensed_600SemiBold,
  BarlowCondensed_700Bold,
  BarlowCondensed_800ExtraBold,
} from '@expo-google-fonts/barlow-condensed';
import {
  JetBrainsMono_400Regular,
  JetBrainsMono_500Medium,
} from '@expo-google-fonts/jetbrains-mono';

export const fontMap = {
  SourceSerif4_400Regular,
  SourceSerif4_400Regular_Italic,
  SourceSerif4_600SemiBold,
  SourceSerif4_700Bold,
  AlbertSans_300Light,
  AlbertSans_400Regular,
  AlbertSans_400Regular_Italic,
  AlbertSans_500Medium,
  AlbertSans_600SemiBold,
  AlbertSans_700Bold,
  BarlowCondensed_600SemiBold,
  BarlowCondensed_700Bold,
  BarlowCondensed_800ExtraBold,
  JetBrainsMono_400Regular,
  JetBrainsMono_500Medium,
} as const;
