// Auto-generated by Style Dictionary — do not edit manually

export const radii = {
  none: 0,
  xs: 4,
  sm: 8,
  md: 16,
  lg: 18,
  xl: 22,
  full: 9999,
  '3xl': 32,
} as const;

export const componentRadius = {
  input: 16,
  buttonOutline: 18,
  buttonPrimary: 9999,
  card: 16,
  highlightRow: 8,
  pill: 9999,
  cardSm: 12,
  modal: 24,
} as const;

export const radius = {
  radii,
  component: componentRadius,
} as const;
