// Auto-generated by Style Dictionary — do not edit manually

export const space = {
  '0': 0,
  '2': 2,
  '4': 4,
  '6': 6,
  '8': 8,
  '10': 10,
  '12': 12,
  '14': 14,
  '16': 16,
  '18': 18,
  '20': 20,
  '22': 22,
  '24': 24,
  '28': 28,
  '32': 32,
  '40': 40,
  '44': 44,
  '48': 48,
  '1': 4,
  '3': 12,
  '5': 20,
  '7': 28,
  px: 1,
} as const;

export const layout = {
  screenPaddingX: 24,
  screenPaddingXAlt: 28,
  tabBarPaddingTop: 18,
  tabBarPaddingBottom: 28,
  screenHorizontal: 20,
  navHeight: 48,
} as const;

export const spacing = {
  space,
  layout,
} as const;
