// Auto-generated by Style Dictionary — do not edit manually

export const fontFamily = {
  sourceSerifRegular: 'SourceSerif4_400Regular',
  sourceSerifItalic: 'SourceSerif4_400Regular_Italic',
  sourceSerifSemiBold: 'SourceSerif4_600SemiBold',
  sourceSerifBold: 'SourceSerif4_700Bold',
  albertSansMedium: 'AlbertSans_500Medium',
  albertSansSemiBold: 'AlbertSans_600SemiBold',
  displaySemiBold: 'BarlowCondensed_600SemiBold',
  displayBold: 'BarlowCondensed_700Bold',
  displayExtraBold: 'BarlowCondensed_800ExtraBold',
  bodyRegular: 'Inter_400Regular',
  bodyMedium: 'Inter_500Medium',
  bodySemiBold: 'Inter_600SemiBold',
  bodyBold: 'Inter_700Bold',
  monoRegular: 'JetBrainsMono_400Regular',
  monoMedium: 'JetBrainsMono_500Medium',
} as const;

export const fontSize = {
  '9': 9,
  '10': 10,
  '11': 11,
  '12': 12,
  '13': 13,
  '14': 14,
  '15': 15,
  '16': 16,
  '17': 17,
  '18': 18,
  '20': 20,
  '22': 22,
  '24': 24,
  '26': 26,
  '28': 28,
  '30': 30,
  '32': 32,
  '34': 34,
  '36': 36,
  '38': 38,
  '44': 44,
  '48': 48,
  '60': 60,
  '72': 72,
  '124': 96,
} as const;

export const lineHeight = {
  tight: '95%',
  compact: '100%',
  normal: '125%',
  relaxed: '150%',
} as const;

export const letterSpacing = {
  displayTight: -0.045,
  displayLoose: -0.03,
  tighter: -0.025,
  tight: -0.02,
  snug: -0.015,
  subtle: -0.005,
  normal: 0,
  wide: 0.2,
  wider: 0.3,
} as const;

export const typeStyles = {
  heroNumeric: {
    fontFamily: 'SourceSerif4_700Bold',
    fontSize: 96,
    lineHeight: 91.2,
    letterSpacing: -4.32,
  },
  heroDisplay: {
    fontFamily: 'SourceSerif4_400Regular_Italic',
    fontSize: 44,
    lineHeight: 41.8,
    letterSpacing: -1.32,
  },
  activeProgress: {
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 28,
    lineHeight: 26.6,
    letterSpacing: -0.84,
  },
  sectionValue: {
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 34,
    lineHeight: 34,
    letterSpacing: -1.02,
  },
  kpiValue: {
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 16,
    lineHeight: 16,
    letterSpacing: -0.4,
  },
  kpiUnit: {
    fontFamily: 'SourceSerif4_400Regular_Italic',
    fontSize: 16,
    lineHeight: 16,
  },
  italicConnector: {
    fontFamily: 'SourceSerif4_400Regular_Italic',
    fontSize: 17,
    lineHeight: 21.25,
    letterSpacing: -0.085,
  },
  buttonPrimary: {
    fontFamily: 'SourceSerif4_600SemiBold',
    fontSize: 18,
    lineHeight: 18,
    letterSpacing: -0.27,
  },
  buttonOutline: {
    fontFamily: 'SourceSerif4_600SemiBold',
    fontSize: 16,
    lineHeight: 16,
    letterSpacing: -0.24,
  },
  textLink: {
    fontFamily: 'SourceSerif4_400Regular_Italic',
    fontSize: 15,
    lineHeight: 15,
    letterSpacing: -0.075,
  },
  segmentInactive: {
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 16,
    lineHeight: 16,
    letterSpacing: -0.24,
  },
  segmentActive: {
    fontFamily: 'SourceSerif4_600SemiBold',
    fontSize: 16,
    lineHeight: 16,
    letterSpacing: -0.24,
  },
  splitsRow: {
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 16,
    lineHeight: 16,
    letterSpacing: -0.24,
  },
  recentRow: {
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 16,
    lineHeight: 16,
    letterSpacing: -0.24,
  },
  labelSection: {
    fontFamily: 'AlbertSans_600SemiBold',
    fontSize: 13,
    lineHeight: 13,
    letterSpacing: 2.6,
    textTransform: 'uppercase' as const,
  },
  labelKpi: {
    fontFamily: 'AlbertSans_500Medium',
    fontSize: 10,
    lineHeight: 10,
    letterSpacing: 3,
    textTransform: 'uppercase' as const,
  },
  labelMicro: {
    fontFamily: 'AlbertSans_500Medium',
    fontSize: 9,
    lineHeight: 9,
    letterSpacing: 2.7,
    textTransform: 'uppercase' as const,
  },
  labelGoalPrefix: {
    fontFamily: 'AlbertSans_600SemiBold',
    fontSize: 11,
    lineHeight: 13.75,
    letterSpacing: 2.2,
    textTransform: 'uppercase' as const,
  },
} as const;

export const display = {
  '2xl': {
    fontFamily: 'BarlowCondensed_700Bold',
    fontSize: 72,
    lineHeight: 79.2,
    letterSpacing: -1.44,
  },
  'xl': {
    fontFamily: 'BarlowCondensed_700Bold',
    fontSize: 60,
    lineHeight: 66,
    letterSpacing: -1.2,
  },
  lg: {
    fontFamily: 'BarlowCondensed_700Bold',
    fontSize: 48,
    lineHeight: 52.8,
    letterSpacing: -0.96,
  },
  md: {
    fontFamily: 'BarlowCondensed_600SemiBold',
    fontSize: 36,
    lineHeight: 45,
    letterSpacing: 0,
  },
  sm: {
    fontFamily: 'BarlowCondensed_600SemiBold',
    fontSize: 30,
    lineHeight: 37.5,
    letterSpacing: 0,
  },
} as const;

export const body = {
  'xl': {
    fontFamily: 'Inter_400Regular',
    fontSize: 20,
    lineHeight: 30,
  },
  lg: {
    fontFamily: 'Inter_400Regular',
    fontSize: 18,
    lineHeight: 27,
  },
  md: {
    fontFamily: 'Inter_400Regular',
    fontSize: 16,
    lineHeight: 24,
  },
  sm: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 21,
  },
  xs: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
} as const;

export const label = {
  lg: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 18,
    lineHeight: 22.5,
  },
  md: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 16,
    lineHeight: 20,
  },
  sm: {
    fontFamily: 'Inter_500Medium',
    fontSize: 14,
    lineHeight: 17.5,
  },
  caps: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 12,
    lineHeight: 15,
    letterSpacing: 1.8,
    textTransform: 'uppercase' as const,
  },
} as const;

export const mono = {
  'xl': {
    fontFamily: 'JetBrainsMono_500Medium',
    fontSize: 20,
    lineHeight: 22,
  },
  lg: {
    fontFamily: 'JetBrainsMono_500Medium',
    fontSize: 18,
    lineHeight: 19.8,
  },
  md: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 16,
    lineHeight: 17.6,
  },
  sm: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 14,
    lineHeight: 15.4,
  },
} as const;

export const typography = {
  fontFamily,
  fontSize,
  lineHeight,
  letterSpacing,
  typeStyles,
  display,
  body,
  label,
  mono,
} as const;
